field.widget.settings.modal_widget:
  type: mapping
  label: 'Modal widget display format settings'
  mapping:
    width:
      type: integer
      label: "Modal width"
    height:
      type: integer
      label: "Modal height"
    override_label:
      type: boolean
      label: "Override label"
    label_singular:
      type: string
      label: "Singular label"
    override_modal_title:
      type: boolean
      label: "Override modal title"
    modal_title:
      type: string
      label: "Modal title"
